<script data-src="{{ asset( 'tags/post-form.tag' ) }}" type="riot/tag"></script>
<script data-src="{{ asset( 'tags/image-form.tag' ) }}" type="riot/tag"></script>
<script data-src="{{ asset( 'tags/video-form.tag' ) }}" type="riot/tag"></script>
<script data-src="{{ asset( 'tags/tag-selector.tag' ) }}" type="riot/tag"></script>
<script data-src="{{ asset( 'tags/tag-infinite-scroller.tag' ) }}" type="riot/tag"></script>
<script data-src="{{ asset( 'tags/friend-renderer.tag' ) }}" type="riot/tag"></script>
<script data-src="{{ asset( 'tags/image-renderer.tag' ) }}" type="riot/tag"></script>
<script data-src="{{ asset( 'tags/video-renderer.tag' ) }}" type="riot/tag"></script>
<script data-src="{{ asset( 'tags/post-renderer.tag' ) }}" type="riot/tag"></script>
<script data-src="{{ asset( 'tags/like-button.tag' ) }}" type="riot/tag"></script>
<script data-src="{{ asset( 'tags/spinner.tag' ) }}" type="riot/tag"></script>
<script data-src="{{ asset( 'tags/image-popup.tag' ) }}" type="riot/tag"></script>
<script data-src="{{ asset( 'tags/video-popup.tag' ) }}" type="riot/tag"></script>
<script data-src="{{ asset( 'tags/comment-section.tag' ) }}" type="riot/tag"></script>